# This workflow will execute .NET code analysis

name: .NET code analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        solution: SpamOK.PasswordGenerator.sln
        build-breaking: true
        all-categories: all
